import type { Metadata } from "next";
import AuthCarousel from "@/components/auth/AuthCarousel";

export const metadata: Metadata = {
    title: "Le Grand",
    description: "Generated by create next app",
};

export default function AuthLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <div className="bg-header-background h-full w-full flex justify-center items-center relative">
            <AuthCarousel className="lg:hidden" />

            {children}
        </div>
    );
}
