import type { Metadata } from "next";
import Header from "@/components/shared/Header";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/shared/AppSidebar";


export const metadata: Metadata = {
    title: "Le Grand",
    description: "Generated by create next app",
};

export default function Layout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <SidebarProvider defaultOpen={false}>
            <AppSidebar />
            <main className="w-full bg-page-background">
                <Header />
                {children}
            </main>
        </SidebarProvider>
    );
}
