import type { Metadata } from "next";
import Header from "@/components/shared/Header";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/shared/AppSidebar";
import { CartProvider } from "@/contexts/CartContext";


export const metadata: Metadata = {
    title: "Le Grand",
    description: "Generated by create next app",
};

export default function Layout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <SidebarProvider defaultOpen={false}>
            <CartProvider>
                <AppSidebar />
                <main className="flex-1 bg-page-background relative">
                    <Header />
                    {children}
                </main>
            </CartProvider>
        </SidebarProvider>
    );
}
