import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
    title: "Le Grand",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="pt-br">
            <body cz-shortcut-listen="true" className="bg-page-background">
                {children}
            </body>
        </html>
    );
}
